# Generated by Django 4.2.3 on 2023-07-13 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mezun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ad', models.CharField(max_length=50)),
                ('soyad', models.CharField(max_length=50)),
                ('mezun_yili', models.IntegerField()),
                ('mezun_bolum', models.CharField(max_length=50)),
                ('mezun_derece', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('sifre', models.CharField(max_length=50, null=True)),
                ('cinsiyet', models.CharField(max_length=50, null=True)),
                ('telefon', models.CharField(max_length=50, null=True)),
                ('adres', models.CharField(max_length=50, null=True, unique=True)),
                ('profil', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
