# Generated by Django 4.2.3 on 2023-07-13 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mesaj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icerik', models.TextField()),
                ('mezun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.mezun')),
            ],
        ),
    ]
