# Generated by Django 4.2.1 on 2023-07-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='adres',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
