# Generated by Django 4.2.1 on 2023-07-22 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_person_adres'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='lisans',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='on_lisans',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='graduate',
            name='yuksek_lisans',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
