# Generated by Django 4.2.1 on 2023-07-22 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_graduate_lisans_graduate_on_lisans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='dogum_tarihi',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='github',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='instagram',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='linkedin',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='twitter',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='universite',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='website',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
