# Generated by Django 4.2.3 on 2023-07-14 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_mezun_last_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mezun',
            name='date_joined',
        ),
    ]
