# Generated by Django 4.2.1 on 2023-07-24 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_event_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100)),
                ('sehir', models.CharField(max_length=100)),
                ('kurulus_yili', models.PositiveIntegerField()),
                ('web_site', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo/')),
                ('adres', models.CharField(max_length=100)),
                ('telefon', models.CharField(max_length=100)),
                ('eposta', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('rektor', models.CharField(max_length=100)),
                ('genel_sekreter', models.CharField(max_length=100)),
                ('baskan', models.CharField(max_length=100)),
                ('profesor_sayisi', models.PositiveIntegerField()),
                ('docent_sayisi', models.PositiveIntegerField()),
                ('ogretim_gorevlisi_sayisi', models.PositiveIntegerField()),
                ('arastirma_gorevlisi_sayisi', models.PositiveIntegerField()),
                ('ogrenci_sayisi', models.PositiveIntegerField()),
                ('lisans_program_sayisi', models.PositiveIntegerField()),
                ('on_lisans_program_sayisi', models.PositiveIntegerField()),
                ('yuksek_lisans_program_sayisi', models.PositiveIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='universite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.universite'),
        ),
    ]
