# Generated by Django 4.2.1 on 2023-07-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_remove_mezun_last_login_remove_mezun_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etkinlikler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etkinlik_adi', models.CharField(max_length=50)),
                ('etkinlik_tarihi', models.DateField()),
                ('etkinlik_yeri', models.CharField(max_length=50)),
                ('etkinlik_suresi', models.CharField(max_length=50)),
                ('etkinlik_katilimcisi', models.CharField(max_length=50)),
                ('etkinlik_icerigi', models.TextField()),
                ('etkinlik_resim', models.FileField(blank=True, null=True, upload_to='')),
                ('etkinlik_video', models.FileField(blank=True, null=True, upload_to='')),
                ('etkinlik_dosya', models.FileField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
