# Generated by Django 4.2.1 on 2023-07-18 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_etkinlikler'),
    ]

    operations = [
        migrations.AddField(
            model_name='mezun',
            name='tc',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='email',
            field=models.EmailField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='profil',
            field=models.ImageField(blank=True, null=True, upload_to='profil/'),
        ),
        migrations.AlterField(
            model_name='mezun',
            name='telefon',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
