# Generated by Django 4.2.1 on 2023-07-24 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_universite_alter_person_universite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='universite',
            old_name='ad',
            new_name='universite_adi',
        ),
        migrations.RenameField(
            model_name='universite',
            old_name='adres',
            new_name='universite_adres',
        ),
        migrations.RenameField(
            model_name='universite',
            old_name='eposta',
            new_name='universite_eposta',
        ),
        migrations.RenameField(
            model_name='universite',
            old_name='telefon',
            new_name='universite_telefon',
        ),
        migrations.AlterField(
            model_name='person',
            name='universite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.universite'),
        ),
    ]
