# Generated by Django 4.2.1 on 2023-07-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_mezun_tc_alter_mezun_email_alter_mezun_profil_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mezun',
            new_name='Graduate',
        ),
    ]
