# Generated by Django 4.2.1 on 2023-07-19 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_mezun_graduate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Etkinlikler',
            new_name='Event',
        ),
    ]
