# Generated by Django 4.2.1 on 2023-07-25 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_graduate_mezun_derece'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='universite_adi',
            new_name='uni_name',
        ),
    ]
