# Generated by Django 4.2.1 on 2023-07-25 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_universite_adi_university_uni_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='uni_name',
            new_name='universite_adi',
        ),
    ]
