# Generated by Django 4.2.1 on 2023-07-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_etkinlik_event_rename_mezun_graduate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='graduate',
            old_name='tc',
            new_name='tc_kimlik_no',
        ),
    ]
