# Generated by Django 4.2.3 on 2023-07-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_rename_uni_name_university_universite_adi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='university',
            old_name='universite_adi',
            new_name='universite_name',
        ),
    ]
