# Generated by Django 4.2.1 on 2023-07-20 09:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0016_message_delete_mesaj'),
    ]

    operations = [
        migrations.AddField(
            model_name='graduate',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
