# Generated by Django 4.2.1 on 2023-07-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_graduate_followers'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowersAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=1000)),
                ('user', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='graduate',
            name='followers',
        ),
    ]
