# Generated by Django 4.2.3 on 2023-08-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_alter_person_github_alter_person_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='facebook',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
