# Generated by Django 4.2.3 on 2023-08-01 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_person_facebook'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='universite_adi',
        ),
        migrations.AddField(
            model_name='event',
            name='mezunlar',
            field=models.ManyToManyField(blank=True, related_name='etkinlikler', to='base.graduate'),
        ),
        migrations.AddField(
            model_name='graduate',
            name='universite_adi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.university'),
        ),
        migrations.AlterField(
            model_name='followersaccount',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followersaccount',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
    ]
