# Generated by Django 4.2.3 on 2023-08-02 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_remove_person_universite_adi_event_mezunlar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
